### ISSUE TITLE
onDropped not working

### ISSUE THREAD

**Issue by ItzTrivialOld** [Mojito-Fivem/npwd-dispatch#2]
Me again. I think the onDropped event doesnt work properly. It doesnt take me out of the dispatch. I even put a console.log in there to check if it does anything, but theres no action, when I commit suicide. 

Thanks for your effort.

**Comment by LiamDormon** [comment]
That's not what onDropped is for...

**Comment by ItzTrivialOld** [comment]
Just noticed, what it is, lol, my bad ^^
